language: node_js
node_js:
    - "6.1"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp mocha phantomjs mocha-phantomjs
# script: mocha-phantomjs test/testrunner.html
after_script:
  - npm run codecov
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
