language: node_js
node_js:
    - "6.1"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp mocha phantomjs casperjs
script: mocha ./test/unit-tests/**/*.test.js --require babel-polyfill --compilers js:babel-register
notifications:
  email: false
